<a href="https://colab.research.google.com/github/scj22/Iftin1/blob/main/faraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd

In [29]:
df=pd.read_csv("fraud_data.csv")

In [30]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0,0.0

In [31]:
df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
97220,10,PAYMENT,17011.46,C1283088834,0.0,0.0,M485693121,0.0,0.0,0.0,0.0
97221,10,PAYMENT,1680.50,C671281,0.0,0.0,M661110294,0.0,0.0,0.0,0.0
97222,10,PAYMENT,26450.83,C948744009,0.0,0.0,M1020130183,0.0,0.0,0.0,0.0
97223,10,PAYMENT,12171.47,C1843902873,0.0,0.0,M2011839805,0.0,0.0,0.0,0.0
97224,10,PAYMENT,6733.59,C708911726,0.0,0.0,M2034482538,0.0,NaN,NaN,NaN

In [32]:
df.shape

(97225, 11)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97225 entries, 0 to 97224
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   step            97225 non-null  int64
 1   type            97225 non-null  object
 2   amount          97225 non-null  float64
 3   nameOrig        97225 non-null  object
 4   oldbalanceOrg   97225 non-null  float64
 5   newbalanceOrig  97225 non-null  float64
 6   nameDest        97225 non-null  object
 7   oldbalanceDest  97225 non-null  float64
 8   newbalanceDest  97224 non-null  float64
 9   isFraud         97224 non-null  float64
 10  isFlaggedFraud  97224 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 8.2+ MB

In [34]:
new_df=df.copy()

In [35]:
new_df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    1
isFraud           1
isFlaggedFraud    1
dtype: int64

In [36]:
new_df["oldbalanceDest"].median()

20808.0

In [37]:
new_df["oldbalanceDest"]=new_df["oldbalanceDest"].fillna(new_df["oldbalanceDest"].median())

In [38]:
new_df["newbalanceDest"]=new_df["newbalanceDest"].fillna(new_df["newbalanceDest"].median())

In [39]:
new_df["isFraud"]=new_df["isFraud"].fillna(new_df["isFraud"].mode()[0])

In [40]:
new_df["isFlaggedFraud"]=new_df["isFlaggedFraud"].fillna(new_df["isFlaggedFraud"].mode()[0])

In [41]:
new_df["newbalanceOrig"]=new_df["newbalanceOrig"].fillna(new_df["newbalanceOrig"].mean())

In [42]:
new_df["nameDest"]=new_df["nameDest"].fillna(new_df["nameDest"].mode()[0])

In [43]:
new_df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [44]:
new_df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
97220,10,PAYMENT,17011.46,C1283088834,0.0,0.0,M485693121,0.0,0.0,0.0,0.0
97221,10,PAYMENT,1680.50,C671281,0.0,0.0,M661110294,0.0,0.0,0.0,0.0
97222,10,PAYMENT,26450.83,C948744009,0.0,0.0,M1020130183,0.0,0.0,0.0,0.0
97223,10,PAYMENT,12171.47,C1843902873,0.0,0.0,M2011839805,0.0,0.0,0.0,0.0
97224,10,PAYMENT,6733.59,C708911726,0.0,0.0,M2034482538,0.0,48944.8,0.0,0.0

In [45]:
new_df[new_df.duplicated(keep="last")]

Empty DataFrame
Columns: [step, type, amount, nameOrig, oldbalanceOrg, newbalanceOrig, nameDest, oldbalanceDest, newbalanceDest, isFraud, isFlaggedFraud]
Index: []

In [46]:
new_df=new_df.drop_duplicates()

In [47]:
new_df.shape

(97225, 11)

In [48]:
new_df["isFlaggedFraud"].value_counts()

isFlaggedFraud
0.0    97225
Name: count, dtype: int64

In [49]:
# new_df['isFraud']=new_df["isFraud"].str.strip().str.capitalize()
# is_fraud_cleaned=new_df["isFraud"].value_counts()
# display(is_fraud_cleaned)

In [50]:
new_df.dropna

<bound method DataFrame.dropna of        step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0         1   PAYMENT   9839.64  C1231006815       170136.0       160296.36
1         1   PAYMENT   1864.28  C1666544295        21249.0        19384.72
2         1  TRANSFER    181.00  C1305486145          181.0            0.00
3         1  CASH_OUT    181.00   C840083671          181.0            0.00
4         1   PAYMENT  11668.14  C2048537720        41554.0        29885.86
...     ...       ...       ...          ...            ...             ...
97220    10   PAYMENT  17011.46  C1283088834            0.0            0.00
97221    10   PAYMENT   1680.50      C671281            0.0            0.00
97222    10   PAYMENT  26450.83   C948744009            0.0            0.00
97223    10   PAYMENT  12171.47  C1843902873            0.0            0.00
97224    10   PAYMENT   6733.59   C708911726            0.0            0.00

          nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud
0      M1979787155             0.0             0.0      0.0             0.0
1      M2044282225             0.0             0.0      0.0             0.0
2       C553264065             0.0             0.0      1.0             0.0
3        C38997010         21182.0             0.0      1.0             0.0
4      M1230701703             0.0             0.0      0.0             0.0
...            ...             ...             ...      ...             ...
97220   M485693121             0.0             0.0      0.0             0.0
97221   M661110294             0.0             0.0      0.0             0.0
97222  M1020130183             0.0             0.0      0.0             0.0
97223  M2011839805             0.0             0.0      0.0             0.0
97224  M2034482538             0.0         48944.8      0.0             0.0

[97225 rows x 11 columns]>

In [58]:
x=new_df.drop(columns=["isFraud"])

In [59]:
x

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
97220,10,PAYMENT,17011.46,C1283088834,0.0,0.00,M485693121,0.0,0.0,0.0
97221,10,PAYMENT,1680.50,C671281,0.0,0.00,M661110294,0.0,0.0,0.0
97222,10,PAYMENT,26450.83,C948744009,0.0,0.00,M1020130183,0.0,0.0,0.0
97223,10,PAYMENT,12171.47,C1843902873,0.0,0.00,M2011839805,0.0,0.0,0.0
97224,10,PAYMENT,6733.59,C708911726,0.0,0.00,M2034482538,0.0,48944.8,0.0

In [60]:
y=new_df['isFraud']

In [61]:
y

0        0.0
1        0.0
2        1.0
3        1.0
4        0.0
        ...
97220    0.0
97221    0.0
97222    0.0
97223    0.0
97224    0.0
Name: isFraud, Length: 97225, dtype: float64

In [62]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score,f1_score,ConfusionMatrixDisplay
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [63]:
x_train, x_text, y_train, y_test = train_test_split(
    x,
    y,
    random_state=42,
    test_size=0.2
)

In [75]:
cat=[
    "type",
    "nameDest",
    "nameOrig"
]
num=[
    "step",
    "amount",
    "oldbalanceOrg",
    "newbalanceOrig",
    "oldbalanceDest",
    "newbalanceDest",
     "isFlaggedFraud"

]

In [84]:
preprocesser=ColumnTransformer([
    ("cat",OneHotEncoder(handle_unknown='ignore'), cat),
    ("num",StandardScaler(),num)
 ]
)

In [85]:
logistic= Pipeline(
    steps=[
        ("preprocessor",preprocesser),
        ("logistic",LogisticRegression())
    ]
)

In [86]:
logistic.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['type', 'nameDest',
                                                   'nameOrig']),
                                                 ('num', StandardScaler(),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest',
                                                   'isFlaggedFraud'])])),
                ('logistic', LogisticRegression())])

In [88]:
y_pred=logistic.predict(x_text)

In [98]:
accuracy=accuracy_score(y_test,y_pred)
precision_score=precision_score(y_test,y_pred)
recall_score=recall_score(y_test,y_pred)
f1_score=f1_score(y_test,y_pred)

print("Accuracy:",accuracy)
print("Precision Score:",precision_score)
print("Recall Score:",recall_score)
print("F1 Score:",f1_score)

Accuracy: 0.9990228850604268
Precision Score: 1.0
Recall Score: 0.05
F1 Score: 0.09523809523809523

In [99]:
import joblib
joblib.dump(logistic,"logistic.joblib")
print("saved seccessfully")

saved seccessfully

In [100]:
random= Pipeline(
    steps=[
        ("preprocessor",preprocesser),
        ("logistic",RandomForestClassifier())
    ]
)

In [101]:
random.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['type', 'nameDest',
                                                   'nameOrig']),
                                                 ('num', StandardScaler(),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest',
                                                   'isFlaggedFraud'])])),
                ('logistic', RandomForestClassifier())])

In [102]:
import joblib
joblib.dump(logistic,"logistic.joblib")
print("saved seccessfully")

saved seccessfully