<a href="https://colab.research.google.com/github/scj22/Iftin1/blob/main/fraud_detection/faraud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("fraud_data.csv")

In [6]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0,0.0

In [7]:
df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
490692,19,CASH_IN,274669.00,C134940126,39016.00,313685.00,C237685833,167627.31,0.00,0.0,0.0
490693,19,CASH_OUT,114040.95,C151790670,282534.35,168493.40,C1991825762,349639.26,522567.44,0.0,0.0
490694,19,CASH_OUT,240854.07,C509260429,168493.40,0.00,C314882858,3026796.40,3486361.48,0.0,0.0
490695,19,CASH_IN,220100.51,C173358966,13036.79,233137.31,C1994989877,248806.95,28706.44,0.0,0.0
490696,19,CASH_IN,67136.31,C1520500247,233137.31,300273.62,C804372771,47.00,NaN,NaN,NaN

In [8]:
df.shape

(490697, 11)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490697 entries, 0 to 490696
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   step            490697 non-null  int64
 1   type            490697 non-null  object
 2   amount          490697 non-null  float64
 3   nameOrig        490697 non-null  object
 4   oldbalanceOrg   490697 non-null  float64
 5   newbalanceOrig  490697 non-null  float64
 6   nameDest        490697 non-null  object
 7   oldbalanceDest  490697 non-null  float64
 8   newbalanceDest  490696 non-null  float64
 9   isFraud         490696 non-null  float64
 10  isFlaggedFraud  490696 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 41.2+ MB

In [10]:
new_df=df.copy()

In [11]:
new_df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    1
isFraud           1
isFlaggedFraud    1
dtype: int64

In [12]:
new_df["oldbalanceDest"].median()

118192.61

In [13]:
new_df["oldbalanceDest"]=new_df["oldbalanceDest"].fillna(new_df["oldbalanceDest"].median())

In [14]:
new_df["newbalanceDest"]=new_df["newbalanceDest"].fillna(new_df["newbalanceDest"].median())

In [15]:
new_df["isFraud"]=new_df["isFraud"].fillna(new_df["isFraud"].mode()[0])

In [16]:
new_df["isFlaggedFraud"]=new_df["isFlaggedFraud"].fillna(new_df["isFlaggedFraud"].mode()[0])

In [17]:
new_df["newbalanceOrig"]=new_df["newbalanceOrig"].fillna(new_df["newbalanceOrig"].mean())

In [18]:
new_df["nameDest"]=new_df["nameDest"].fillna(new_df["nameDest"].mode()[0])

In [19]:
new_df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [20]:
new_df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
490692,19,CASH_IN,274669.00,C134940126,39016.00,313685.00,C237685833,167627.31,0.00,0.0,0.0
490693,19,CASH_OUT,114040.95,C151790670,282534.35,168493.40,C1991825762,349639.26,522567.44,0.0,0.0
490694,19,CASH_OUT,240854.07,C509260429,168493.40,0.00,C314882858,3026796.40,3486361.48,0.0,0.0
490695,19,CASH_IN,220100.51,C173358966,13036.79,233137.31,C1994989877,248806.95,28706.44,0.0,0.0
490696,19,CASH_IN,67136.31,C1520500247,233137.31,300273.62,C804372771,47.00,222182.32,0.0,0.0

In [21]:
new_df[new_df.duplicated(keep="last")]

Empty DataFrame
Columns: [step, type, amount, nameOrig, oldbalanceOrg, newbalanceOrig, nameDest, oldbalanceDest, newbalanceDest, isFraud, isFlaggedFraud]
Index: []

In [22]:
new_df=new_df.drop_duplicates()

In [23]:
new_df.shape

(490697, 11)

In [24]:
new_df["isFlaggedFraud"].value_counts()

isFlaggedFraud
0.0    490697
Name: count, dtype: int64

In [25]:
# new_df['isFraud']=new_df["isFraud"].str.strip().str.capitalize()
# is_fraud_cleaned=new_df["isFraud"].value_counts()
# display(is_fraud_cleaned)

In [26]:
x=new_df.drop(columns="isFraud")

In [27]:
x

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.00,0.00,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.00,0.00,0.0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,0.0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...
490692,19,CASH_IN,274669.00,C134940126,39016.00,313685.00,C237685833,167627.31,0.00,0.0
490693,19,CASH_OUT,114040.95,C151790670,282534.35,168493.40,C1991825762,349639.26,522567.44,0.0
490694,19,CASH_OUT,240854.07,C509260429,168493.40,0.00,C314882858,3026796.40,3486361.48,0.0
490695,19,CASH_IN,220100.51,C173358966,13036.79,233137.31,C1994989877,248806.95,28706.44,0.0
490696,19,CASH_IN,67136.31,C1520500247,233137.31,300273.62,C804372771,47.00,222182.32,0.0

In [28]:
y=new_df["isFraud"]

In [29]:
y

0         0.0
1         0.0
2         1.0
3         1.0
4         0.0
         ...
490692    0.0
490693    0.0
490694    0.0
490695    0.0
490696    0.0
Name: isFraud, Length: 490697, dtype: float64

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [31]:
X_train,X_test,y_train,y_test= train_test_split (
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [32]:
cat=[
 "type",
 "nameOrig",
 "nameDest"

]

In [33]:
num=[
    "step",
    "amount",
    "oldbalanceOrg",
    "newbalanceOrig",
    "oldbalanceDest",
    "newbalanceDest",
    "isFlaggedFraud"

]

In [34]:
prepocessing = ColumnTransformer([
    ("cat",OneHotEncoder(handle_unknown="ignore"),cat),
    ("num",StandardScaler(),num)
])

In [35]:
logistic = Pipeline([
    ("preprocessor",prepocessing),
    ("model",LogisticRegression())
])

In [36]:
logistic.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['type', 'nameOrig',
                                                   'nameDest']),
                                                 ('num', StandardScaler(),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest',
                                                   'isFlaggedFraud'])])),
                ('model', LogisticRegression())])

In [37]:
y_pred=logistic.predict(x_test)

In [38]:
accuracy=accuracy_score(y_test,y_pred)
precision_scr=precision_score(y_test,y_pred)
recall_scr=recall_score(y_test,y_pred)
f1_scr=f1_score(y_test,y_pred)

print("Accuracy:",accuracy)
print("Precision Score:",precision_scr)
print("Recall Score:",recall_scr)
print("F1 Score:",f1_scr)

Accuracy: 0.9996026085184431
Precision Score: 1.0
Recall Score: 0.09302325581395349
F1 Score: 0.1702127659574468

In [39]:
import joblib
joblib.dump(logistic, "logistic_model.joblib")
print("Model saved successfully!")

Model saved successfully!

In [40]:
random = Pipeline([
    ("preprocessor",prepocessing),
    ("model",RandomForestClassifier())
])

In [41]:
random.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['type', 'nameOrig',
                                                   'nameDest']),
                                                 ('num', StandardScaler(),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest',
                                                   'isFlaggedFraud'])])),
                ('model', RandomForestClassifier())])

In [42]:
y_predict=random.predict(X_test)

In [45]:
rf_accuracy = accuracy_score(y_test, y_predict)
rf_precision = precision_score(y_test, y_predict)
rf_recall = recall_score(y_test, y_predict)
rf_f1 = f1_score(y_test, y_predict)

print("===== Random Forest Results =====")
print("Accuracy:", rf_accuracy)
print("Precision Score:", rf_precision)
print("Recall Score:", rf_recall)
print("F1 Score:", rf_f1)

===== Random Forest Results =====
Accuracy: 0.9996026085184431
Precision Score: 1.0
Recall Score: 0.09302325581395349
F1 Score: 0.1702127659574468

In [46]:
joblib.dump(random, "random_forest.joblib")
print("Model saved successfully!")

Model saved successfully!