<a href="https://colab.research.google.com/github/scj22/Iftin1/blob/main/machine-learning/student_at_risk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd

In [17]:
df= pd.read_csv("student-por.csv",sep=";")

In [18]:
df.head()

  school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        4   0  11  11
1     GP   F   17       U     GT3       T  ...     1       3        2   9  11  11
2     GP   F   15       U     LE3       T  ...     3       3        6  12  13  12
3     GP   F   15       U     GT3       T  ...     1       5        0  14  14  14
4     GP   F   16       U     GT3       T  ...     2       5        0  11  13  13

[5 rows x 33 columns]

In [19]:
df.tail()

    school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
644     MS   F   19       R     GT3       T  ...     2       5        4  10  11  10
645     MS   F   18       U     LE3       T  ...     1       1        4  15  15  16
646     MS   F   18       U     GT3       T  ...     1       5        6  11  12   9
647     MS   M   17       U     LE3       T  ...     4       2        6  10  10  10
648     MS   M   18       R     LE3       T  ...     4       5        4  10  11  11

[5 rows x 33 columns]

In [20]:
df.shape

(649, 33)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

# Day 2 EDA

In [22]:
new_df = df.copy()

In [23]:
new_df.isnull().sum()

# isn()
new_df.isna().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [24]:
# drop()
new_df.drop(columns=["school"])
new_df


# drop index
new_df.drop(index=0)

    school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
1       GP   F   17       U     GT3       T  ...     1       3        2   9  11  11
2       GP   F   15       U     LE3       T  ...     3       3        6  12  13  12
3       GP   F   15       U     GT3       T  ...     1       5        0  14  14  14
4       GP   F   16       U     GT3       T  ...     2       5        0  11  13  13
5       GP   M   16       U     LE3       T  ...     2       5        6  12  12  13
..     ...  ..  ...     ...     ...     ...  ...   ...     ...      ...  ..  ..  ..
644     MS   F   19       R     GT3       T  ...     2       5        4  10  11  10
645     MS   F   18       U     LE3       T  ...     1       1        4  15  15  16
646     MS   F   18       U     GT3       T  ...     1       5        6  11  12   9
647     MS   M   17       U     LE3       T  ...     4       2        6  10  10  10
648     MS   M   18       R     LE3       T  ...     4       5        4  10  11  11

[648 rows x 33 columns]

In [25]:
# dropna()
new_df.dropna()

# subset
new_df.dropna(subset=["school"])

    school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0       GP   F   18       U     GT3       A  ...     1       3        4   0  11  11
1       GP   F   17       U     GT3       T  ...     1       3        2   9  11  11
2       GP   F   15       U     LE3       T  ...     3       3        6  12  13  12
3       GP   F   15       U     GT3       T  ...     1       5        0  14  14  14
4       GP   F   16       U     GT3       T  ...     2       5        0  11  13  13
..     ...  ..  ...     ...     ...     ...  ...   ...     ...      ...  ..  ..  ..
644     MS   F   19       R     GT3       T  ...     2       5        4  10  11  10
645     MS   F   18       U     LE3       T  ...     1       1        4  15  15  16
646     MS   F   18       U     GT3       T  ...     1       5        6  11  12   9
647     MS   M   17       U     LE3       T  ...     4       2        6  10  10  10
648     MS   M   18       R     LE3       T  ...     4       5        4  10  11  11

[649 rows x 33 columns]

In [26]:
# filnna()
new_df["school"].mode()

0    GP
Name: school, dtype: object

In [27]:
new_df["school"]=new_df["school"].fillna(new_df["school"].mode()[0])

In [28]:
# numerical
new_df["age"].median()

17.0

In [29]:
new_df["age"].fillna(new_df["age"].median()).astype(int)

0      18
1      17
2      15
3      15
4      16
       ..
644    19
645    18
646    18
647    17
648    18
Name: age, Length: 649, dtype: int64

In [30]:
# dupliactes
# False, first,last
new_df[new_df.duplicated(keep="last")]

Empty DataFrame
Columns: [school, sex, age, address, famsize, Pstatus, Medu, Fedu, Mjob, Fjob, reason, guardian, traveltime, studytime, failures, schoolsup, famsup, paid, activities, nursery, higher, internet, romantic, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3]
Index: []

In [31]:
new_df=new_df.drop_duplicates()

In [32]:
new_df.head()

  school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        4   0  11  11
1     GP   F   17       U     GT3       T  ...     1       3        2   9  11  11
2     GP   F   15       U     LE3       T  ...     3       3        6  12  13  12
3     GP   F   15       U     GT3       T  ...     1       5        0  14  14  14
4     GP   F   16       U     GT3       T  ...     2       5        0  11  13  13

[5 rows x 33 columns]

In [33]:
new_df["at_risk"]=(new_df["G3"]<10).astype(int)

In [34]:
new_df.head()

  school sex  age address famsize  ... absences  G1  G2  G3 at_risk
0     GP   F   18       U     GT3  ...        4   0  11  11       0
1     GP   F   17       U     GT3  ...        2   9  11  11       0
2     GP   F   15       U     LE3  ...        6  12  13  12       0
3     GP   F   15       U     GT3  ...        0  14  14  14       0
4     GP   F   16       U     GT3  ...        0  11  13  13       0

[5 rows x 34 columns]

In [35]:
features = [
    "studytime", "failures", "schoolsup", "famsup", "activities",
    "higher", "internet", "famrel", "health", "absences"
]

X=new_df[features].copy()

In [36]:
X

     studytime  failures schoolsup famsup  ... internet famrel health  absences
0            2         0       yes     no  ...       no      4      3         4
1            2         0        no    yes  ...      yes      5      3         2
2            2         0       yes     no  ...      yes      4      3         6
3            3         0        no    yes  ...      yes      3      5         0
4            2         0        no    yes  ...       no      4      5         0
..         ...       ...       ...    ...  ...      ...    ...    ...       ...
644          3         1        no     no  ...      yes      5      5         4
645          2         0        no    yes  ...      yes      4      1         4
646          2         0        no     no  ...       no      1      5         6
647          1         0        no     no  ...      yes      2      2         6
648          1         0        no     no  ...      yes      4      5         4

[649 rows x 10 columns]

In [37]:
Y=new_df["at_risk"]

In [38]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
644    0
645    0
646    1
647    0
648    0
Name: at_risk, Length: 649, dtype: int64

In [39]:
class_balance= Y.value_counts()

In [40]:
class_balance

at_risk
0    549
1    100
Name: count, dtype: int64

In [41]:
model_data=X.copy()

In [42]:
model_data["at_risk"]=Y

In [43]:
model_data.head()

   studytime  failures schoolsup famsup  ... famrel health absences  at_risk
0          2         0       yes     no  ...      4      3        4        0
1          2         0        no    yes  ...      5      3        2        0
2          2         0       yes     no  ...      4      3        6        0
3          3         0        no    yes  ...      3      5        0        0
4          2         0        no    yes  ...      4      5        0        0

[5 rows x 11 columns]

In [44]:
model_data.to_csv(
    "student-cleaned-data.csv",
    index=False
)

In [50]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

In [54]:
x=model_data.drop(columns="at_risk")

In [55]:
X

     studytime  failures schoolsup famsup  ... internet famrel health  absences
0            2         0       yes     no  ...       no      4      3         4
1            2         0        no    yes  ...      yes      5      3         2
2            2         0       yes     no  ...      yes      4      3         6
3            3         0        no    yes  ...      yes      3      5         0
4            2         0        no    yes  ...       no      4      5         0
..         ...       ...       ...    ...  ...      ...    ...    ...       ...
644          3         1        no     no  ...      yes      5      5         4
645          2         0        no    yes  ...      yes      4      1         4
646          2         0        no     no  ...       no      1      5         6
647          1         0        no     no  ...      yes      2      2         6
648          1         0        no     no  ...      yes      4      5         4

[649 rows x 10 columns]

In [56]:
y=model_data["at_risk"]

In [57]:
y

0      0
1      0
2      0
3      0
4      0
      ..
644    0
645    0
646    1
647    0
648    0
Name: at_risk, Length: 649, dtype: int64

In [76]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2,
    random_state=42)

In [62]:
num= [
    "studytime",
    "failures",
    "famrel",
    "health",
    "absences"
]

cat= [
    "schoolsup",
    "famsup",
    "activities",
    "higher",
    "internet"
]

In [63]:
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), num),
    ("cat", OneHotEncoder(), cat)
])

In [64]:
dt_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', DecisionTreeClassifier(random_state=42))
])

In [67]:
dt_pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['studytime', 'failures',
                                                   'famrel', 'health',
                                                   'absences']),
                                                 ('cat', OneHotEncoder(),
                                                  ['schoolsup', 'famsup',
                                                   'activities', 'higher',
                                                   'internet'])])),
                ('model', DecisionTreeClassifier(random_state=42))])

In [69]:
y_pred=dt_pipeline.predict(X_test)

In [75]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.8307692307692308
Precision: 0.3333333333333333
Recall   : 0.4666666666666667
F1 Score : 0.3888888888888889